Shopify/active_shipping

CONTRIBUTING.md, README.md
@RichardBlair @robfoster as discussed.
=> CONTRIBUTING guidelines

.gitignore, .travis.yml, Gemfile.activesupport32, Gemfile.activesupport40, Gemfile.activesupport41, Gemfile.activesupport42, active_shipping.gemspec, test/test_helper.rb
@kmcphillips @RichardBlair @robfoster FYI.
=> Fix Gemfiles to make sure the right versions of activesupport are loaded

active_shipping.gemspec, test/test_helper.rb
=> Bump mocha to 1.1

lib/active_shipping/carriers/kunaki.rb
Remote tests are working too.
@Shopify/shipping for review.
=> Convert Kunaki from REXML/Builder to Nokogiri

lib/active_shipping/carrier.rb, lib/active_shipping/carriers/ups.rb, test/fixtures/xml/ups/test_real_home_as_residential_destination_response_with_insured.xml, test/remote/ups_test.rb
Except for some tests that are skipped, remote tests pass as well.
=> UPS: port XML processing to Nokogiri

lib/active_shipping/carriers/shipwire.rb, test/unit/carriers/shipwire_test.rb
@Shopify/shipping surprise! Another one. All tests pass.
=> Convert shipwire to nokogiri

lib/active_shipping/carriers/ups.rb, lib/active_shipping/carriers/usps.rb, test/fixtures/xml/usps/us_rate_request.xml, test/fixtures/xml/usps/world_rate_request_with_value.xml, test/fixtures/xml/usps/world_rate_request_without_value.xml, test/remote/usps_test.rb, test/unit/carriers/usps_test.rb
@Shopify/shipping For review. Remote tests work as well.
=> Convert USPS to nokogiri

lib/active_shipping/carriers/stamps.rb, test/remote/stamps_test.rb
- Generate XML using Nokogiri
- Also, stamps.com actually managed to update their SSL implementation, so we no longer require SSLv3.
=> Convert stamps to nokogiri

lib/active_shipping/carriers/canada_post_pws.rb, test/unit/carriers/canada_post_pws_rating_test.rb, test/unit/carriers/canada_post_pws_shipping_test.rb
Pretty straightforward conversion.
=> [Canada Post AWS] Convert XML processing to Nokogiri

lib/active_shipping/carriers/fedex.rb, lib/active_shipping/carriers/ups.rb, lib/active_shipping/version.rb, test/fixtures/xml/fedex/tracking_response_with_blank_state.xml, test/unit/carriers/fedex_test.rb
if city or state/province in a fedex tracking response is blank defaults to unknown.
=> FedEx tracking response city and state/province defaults to unknown if empty

lib/active_shipping/carriers/usps.rb
start_with rather than starts_with
=> Fix start_with method call

lib/active_shipping.rb
Fixes the root cause of the error encountered in #273.
@kmcphillips
=> Require all of active_support.

test/remote/fedex_test.rb
Updates the tracking tests with tracking numbers that actually work.
These are all test tracking numbers from FedEx.
@kmcphillips
=> Fix Fedex remote tests

CHANGELOG.md, lib/active_shipping/version.rb
Deploy some fixes
@kmcphillips
=> Bump version to v1.4.1

lib/active_shipping/carriers/ups.rb, test/unit/carriers/ups_test.rb
Parse the type code of each shipment event in tracking response.
=> Ups shipment event code

lib/active_shipping/rate_estimate.rb, test/unit/rate_estimate_test.rb
@kmcphillips @garethson for review please, thanks.
=> Add compare_price to rate estimate

test/remote/usps_test.rb
@lucasuyezu @mdking 
Fixing this test separately so I can more confidently merge other PRs. Don't like having a red build.
=> Use a new valid tracking number for USPS remote test

lib/active_shipping/carriers/ups.rb, test/remote/ups_test.rb
This fixes and closes PR #316 too.
=> Add UPS support for other labels like ZPL, EPL STARPL and SPL

lib/active_shipping/carriers/fedex.rb, test/unit/carriers/fedex_test.rb
See https://github.com/Shopify/active_shipping/issues/307
The ```parse_rate_response``` method would crash and return a NoMethodError whenever the service type was missing in the XML response from FEDEX.
This seems to be related to the new version of the upstream API. As a workaround before we implement this new version, this PR proposes to catch all NoMethodErrors in ```the parse_rate_response``` loop through the rates, and return as much as possible.
Because of this, the rates list might contain nil values, hence it will be compacted and also kept as successful, as not to raise an exception afterward, while logging the faulty XML response.
=> Catch NoMethodErrors in FEDEX find_and_parse_rate method

lib/active_shipping/rate_estimate.rb
Small refactor on `rate_estimate` that moves the private method to a protected visibility and creates a setter for `delivery_range`.
cc/ @jonathankwok @cyprusad
=> Refactored setters on rate estimate

lib/active_shipping/carrier.rb
=> Fix typo in Carrier.rb

lib/active_shipping/tracking_response.rb
Fixes possible typo on line 85
=> Fix typo in tracking_response.rb

lib/active_shipping/tracking_response.rb
On line 5, change "that" to "than"
=> Fix typo in tracking_resonse.rb

lib/active_shipping/shipping_response.rb
On line 9, change "witch" to "which"
=> Fix typo in shipping_response.rb

lib/active_shipping/carrier.rb, lib/active_shipping/carriers/ups.rb
I've been reading through the UPS Carrier class and documenting some of it. I also found some typos in the Carrier class.
=> [ci skip] Document a UPS method & Fix some typos

.travis.yml, Gemfile.activesupport_master
@thegedge @jonathankwok @sgrif 
https://twitter.com/sgrif/status/804037955241312258
Let's run our CI against rails master.
The matrix is silly big right now. But we can be opinionated in the 2.0 branch and drop support for anything below 4.2.
=> Run CI against rails master

README.md
This is the last change I am going to introduce to master before branching.
I'll merge this and ship version `1.9` and create the branch `1-9-stable`.
Then onward and upward to `2.0`. I've got a bunch of changes on branches.
@mdking @jonathankwok @thegedge
=> Add 1.x vs 2.x notes to README

active_shipping.gemspec, lib/active_shipping.rb, lib/active_shipping/carrier.rb, lib/active_shipping/carriers/australia_post.rb, lib/active_shipping/carriers/usps.rb, lib/active_shipping/package.rb, lib/active_shipping/package_item.rb, test/fixtures/xml/canadapost/example_request.xml, test/unit/carrier_test.rb, test/unit/carriers/australia_post_test.rb, test/unit/carriers/new_zealand_post_test.rb, test/unit/package_item_test.rb, test/unit/package_test.rb, test/unit/shipment_packer_test.rb
The changes are pretty simple - Everything still seems to work.
=> Main commit getting rid of Quantified dependency - And replacing with Measured 1.6.0

test/unit/rate_estimate_test.rb
1. Use `test "" do` syntax.
2. That's pretty much it. 
I probably could've put this in the same PR as #462
=> Modernize RateEstimateTest

active_shipping.gemspec
Debugging code, now with 100% more stepping and nexting!
=> Add pry-byebug to development dependencies

lib/active_shipping/shipment_packer.rb
No functionality change here, just cleaning this method up in an attempt to make it more readable. I've noticed there might be a bug in how we pack some items here, and I will follow up with a fix + explanation. But for now, just prepping to make the change easy :)
=> Clean up ShipmentPacker#pack

.gitignore
=> add .byebug_history to .gitignore

lib/active_shipping/carriers/canada_post_pws.rb
Removing `gsub!` from Canada post PWS as everything is referenced in Ruby this causes some issues where the location you created using `ActiveShipping::Location#from` ends up modifying the original object (which has many undesirable effects)
=> remove gsub! form canada_post_pws

active_shipping.gemspec, lib/active_shipping/carriers/canada_post.rb, lib/active_shipping/carriers/canada_post_pws.rb, lib/active_shipping/package.rb, lib/active_shipping/package_item.rb, test/unit/package_item_test.rb
Bumps [measured](https://github.com/Shopify/measured) to 2.0.
Diff https://github.com/Shopify/measured/compare/v1.6.0...v2.0.0
Addresses https://github.com/Shopify/active_shipping/issues/461.
=> Bump measured to 2.0

lib/active_shipping/version.rb
As we work towards a 2.0, let's set this version to what it really is.
=> Bump master version gemspec.

CHANGELOG.md, CONTRIBUTING.md, README.md, active_shipping.gemspec, lib/active_shipping/version.rb
Updates ActiveShipping to version 2.0.0.
=> Update to version 2.0.
