Shopify/active_shipping

active_shipping.gemspec

This restricts the dependency to certain version ranges.
- Most of the versions I copied from activemerchant. 
- I removed `json` because it is part of the standard library in Ruby 1.9+. We dropped support for Ruby 1.8
@robfoster @RichardBlair

Restrict dependency versions in gemspec

---

active_shipping.gemspec
lib/active_shipping.rb
lib/active_shipping/carriers/canada_post.rb
test/fixtures/xml/canadapost/example_request.xml
test/fixtures/xml/canadapost/example_response_with_nil_value.xml
test/unit/carriers/canada_post_test.rb

This updates the legacy Canada Post carrier to use Nokogiri to generate XML requests and parse XML responses, instead of XmlNode and REXML respectively.
I'd like to get rid of XmlNode and standardize on Nokogiri for XML processing. This is one step in that direction. The other option is to standardize on REXML + Builder. Nokogiri is fasterand built on top of a battle tested libxml, but REXML + Builder are pure Ruby. What do you think?

Canada Post with nokogiri

---

.gitignore
.yardopts
README.md
lib/active_shipping/carrier.rb

This adds Yardoc documentation to the `ActiveShipping::Carrier` class.
Some of the helper classes and response classes definitely need documentation too, but given that the Carrier primarily defines the abstraction, this is a good place to start.
Once we do a release, the docs should show up here: http://www.rubydoc.info/gems/active_shipping
@kmcphillips @jnormore @garethson

Document ActiveShipping::Carrier using yardoc.

---

.gitignore
lib/active_shipping/carrier.rb
lib/active_shipping/label_response.rb
lib/active_shipping/rate_estimate.rb
lib/active_shipping/rate_response.rb
lib/active_shipping/response.rb
lib/active_shipping/shipment_packer.rb
lib/active_shipping/shipping_response.rb
lib/active_shipping/tracking_response.rb

This adds some documentation for the different response classes.
I tried to do this as well as possible, but the different carriers are not necessarily consistent in what values they assign to the different attributes in the response objects. Not sure if we want to tackle these; for now I left the scope of this PR to docs only.

Rdoc for response classes

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/tracking_response_failure.xml

@Shopify/shipping This one fell trough the cracks.

Fixes a remote tests for USPS: raise an exception if the tracking number is not found.

---

.travis.yml
Rakefile
test/credentials.yml
test/remote/canada_post_pws_platform_test.rb
test/remote/canada_post_pws_test.rb
test/remote/canada_post_test.rb
test/remote/fedex_test.rb
test/remote/new_zealand_post_test.rb
test/remote/shipwire_test.rb
test/remote/stamps_test.rb
test/remote/ups_test.rb
test/remote/usps_test.rb
test/test_helper.rb
test/unit/carriers/canada_post_pws_rating_test.rb
test/unit/carriers/canada_post_pws_register_test.rb
test/unit/carriers/canada_post_pws_shipping_test.rb
test/unit/carriers/canada_post_pws_tracking_test.rb
test/unit/carriers/canada_post_test.rb
test/unit/carriers/usps_test.rb
test/unit/rate_estimate_test.rb

Hello @Shopify/shipping, it's me again! :) 
- Pass credentials.yml through ERB, so we can populate it with values from environment variables.
- Skip remote tests when asking for credentials, but none are set in `credentials.yml`.
- Make sure remote test class names are prefixed with Remote, and do not clash with unit test class names.
- Set up Travis to also run remote tests.
I added the test API keys for Canada Post and New Zealand Post to the Travis environment. These credentials were already made public in `credentials.yml`, so I assume that's OK. For the other ones, we can use [Travis's encrypted environment variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables).

Update test framework so remote tests can be run on CI

---

lib/active_shipping/carriers/canada_post_pws.rb
test/remote/canada_post_pws_platform_test.rb

Now also the platform tests work again.
I had to reinstate an `unnormalize` call, because REXML doesn't deal with characters encoding using entities well (e.g. `&#123;` => `à`. I will fix this when moving to Nokogiri.

[Canada Post PWS] Fix remote platform tests

---

lib/active_shipping/carriers/usps.rb
test/remote/usps_test.rb

* Refactoring caused a NPE by calling .text on a non-existant XML path
* Add test coverage to the validation method
* Fix the NPE
@Shopify/shipping @wvanbergen

fix null pointer exception in usps validate

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/delivered_extended_tracking_response.xml
test/unit/carriers/usps_test.rb

USPS seem to have a different format for the `TrackSummary` element in `TrackResponse`, than the one expected by ActiveShipping.
Currently something along the lines of `Your item was delivered at 2:16 pm on October 12, 2013 in BROOKLYN, NY 11201.` is expected, however, sometimes (always?) there's extra information, i.e. `Your item was delivered to the front desk or reception area at 2:16 pm on October 12, 2013 in BROOKLYN, NY 11201.`, or `Your item was delivered in or at the mailbox at 2:16 pm on October 12, 2013 in BROOKLYN, NY 11201.`
This fixes the regex in the USPS carrier to take this into account, and should also fix #205.

Fix USPS tracking not parsed as 'delivered'

---

lib/active_shipping/carriers/ups.rb
test/credentials.yml
test/remote/ups_test.rb
test/test_helper.rb
test/unit/carriers/ups_test.rb

This adds some more options to create_shipment for UPS.
I believe these options are necessary for shipping internationally.
They are definitely necessary for making use of paperless_invoice which allows one to ship commercial packages internationally without printing out a customs invoice.

Add more options to UPS create_shipment

---

lib/active_shipping/carriers/ups.rb
test/unit/carriers/ups_test.rb

I pulled this out of #202 to provide support for all of UPS's delivery confirmation options.
I translated it to nokogiri and added some logic to deal with shipment-level vs package-level delivery confirmation stuff. 
UPS specifies that for certain origin/destination pairs delivery_confirmation options must be specified on the shipment-level, for other origin/destination pairs that option must be specified on each package in the shipment.
As it's written a user can pass in delivery_confirmation as an option and it will be used shipment-level or applied to each package based on the origin/destination pair. If the user would like to specify different delivery_confirmation options for each package in the shipment she can do so by specifying a value in the package.options hash for each …

UPS. Better support for delivery confirmation options

---

Rakefile

Removes the `k` in `functional`

Fix typo in task description

---

active_shipping.gemspec
lib/active_shipping/carriers/ups.rb
lib/active_shipping/delivery_date_estimate.rb
test/credentials.yml
test/fixtures/xml/ups/rate_single_service.xml
test/remote/ups_test.rb
test/test_helper.rb
test/unit/carriers/ups_test.rb

Fixed some issues I found with how the delivery_dates tests were written. UPS would fail with an invalid pickup date exception. I also added support to get rates for only a single service from UPS.

Fix tests and add single service rates to UPS

---

active_shipping.gemspec

Bumping Quantified version to pull changes introduced in https://github.com/Shopify/quantified/pull/4
cc. @wvanbergen

Bump Quantified: 1.0.0 -> 1.0.1

---

lib/active_shipping/carriers/usps.rb
test/unit/carriers/usps_test.rb

When no container type is specified we set the container type to `<Container/>`. On large packages (packages with at least one dimension greater than 1 foot) the rate response comes back but is incorrect.
Choose a container type when non is specified. 
* A container type was being specified for international rate requests
@Shopify/shipping @wvanbergen

USPS US to US rate requests must specify a container type

---

CHANGELOG.md
README.md
lib/active_shipping/version.rb

@Shopify/shipping Let's get this out of the door so people stop complaining about the latest ActiveMerchant and ActiveShipping causing naming conflicts.

Prepare for release of v1.0.0

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb

The time in transit API requires weight info when you're using it for international shipments.
Also, tests were failing for UPS because I hardcoded February 1st into the tests in a few places not realizing that UPS doesn't not permit you to make requests about dates that are more than 60 days (I think?) in the future or past. This fixes that. Although I think these tests will still fail right around holidays, that's a problem to be fixed at some point I suppose.

UPS: Add Weight to delivery dates request so it works internationally.

---

CHANGELOG.md
lib/active_shipping/carriers/usps.rb
lib/active_shipping/version.rb
test/fixtures/xml/usps/tracking_response_alt.xml
test/unit/carriers/usps_test.rb

In #260 I assumed some fields would always be present that are in fact optional. This caused errors when for example, tracking a number with no predicted delivery date yet.
This PR passes through nil values for those fields instead of throwing an error. Only the predicted delivery dates have been observed to be missing but this PR also speculatively allows the location to be optional since some more obscure events like "seized by law enforcement" may not have a location. 

Fix USPS tracking bug

---

lib/active_shipping/carriers/usps.rb
lib/active_shipping/version.rb
test/unit/carriers/usps_test.rb

The existing code for error message extraction wasn't tested, and was totally wrong.
- `document.elements[...]` doesn't search the document, it indexes an array.
- failed searches return an empty array-ish-thing not nil so `first_thing || second_thing` doesn't work
- Same thing made the checking multiple xpaths pattern not work, replaced it with a single general xpath.
I'm ashamed that I didn't have to Google the xpath syntax. I try to repress the memories of my days working with XSLT.

Fix finding of error description in USPS tracking

---

lib/active_shipping/carriers/ups.rb
test/fixtures/xml/ups/access_request.xml
test/fixtures/xml/ups/tracking_request.xml
test/unit/carriers/ups_test.rb

In order to track a UPS Mail Innovations tracking number in the API, you must also include the TrackingOption which is 03.
Here is an example of what the request would look like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<AccessRequest xml:lang="en-US">
<AccessLicenseNumber>Your Access Key</AccessLicenseNumber>
<UserId>Your User ID</UserId>
<Password>Your Password</Password>
</AccessRequest>
<?xml version="1.0" encoding="UTF-8"?>
<TrackRequest>
<TrackingOption>03</TrackingOption>
<Request>
<TransactionReference/>
</Request>
<RequestAction>Track</RequestAction>
<RequestOption>1</RequestOption>
<TrackingNumber>1234567890</TrackingNumber>
</TrackRequest>
```

UPS - add tracking_option on tracking info request

---

lib/active_shipping/carriers/usps.rb
lib/active_shipping/version.rb
test/unit/carriers/usps_test.rb

Currently tracking API calls fail in an invalid-schema kind of way if the zip code format is invalid. [ZIP+4](https://en.wikipedia.org/wiki/ZIP_code#ZIP.2B4) is considered an invalid format. This PR trims the first 5 digits to turn a ZIP+4 into a valid normal ZIP.

Handle ZIP+4 by trimming.

---

test/remote/correios_test.rb

Because travis tests 12 different versions and one of these tests fails I'd estimate around 10% of the time basic statistics tells us that these tests will break CI 70% of the time.
So we kill them :fire: 
@kmcphillips

Skip remote Correios tests, they are unreliable.

---

lib/active_shipping/rate_estimate.rb
test/unit/rate_estimate_test.rb

This adds a field for rate estimate references for services that guarantee quotes.
Review @kmcphillips @j-mutter

add reference for estimates

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/tracking_request_batch.xml
test/fixtures/xml/usps/tracking_response_batch.xml
test/unit/carriers/usps_test.rb

Adds a method `batch_find_tracking_info` that allows fetching the tracking info for multiple numbers at a time. It accepts an array of hashes with all the info necessary to uniquely specify a shipment and returns an array of results in the same order.
USPS has two types of errors, schema errors that wreck the whole request, which are thrown as exceptions, and individual errors that only affect a certain tracker, which are just returned as unsuccessful responses.
Both the single and batched methods use the same parsing and building methods behind the scenes.

Add support for batch tracking info fetching on USPS

---

lib/active_shipping/carriers/fedex.rb
test/remote/fedex_test.rb

As discussed in #261 the `create_shipment` interface accepts an array but the FedEx code doesn't support multiple packages yet. This just turns a comment caveat into an exception and then tests the interface.
@kmcphillips

Error handling for FedEx unsupported multiple packages.

---

lib/active_shipping/carriers/usps.rb
lib/active_shipping/version.rb
test/fixtures/xml/usps/world_rate_request_with_value.xml
test/fixtures/xml/usps/world_rate_request_without_value.xml
test/unit/carriers/usps_test.rb

This fixes the issues introduced by the USPS WEBTOOLS upgrade on May 31. This patch has been tested to work in retrieving international rates from the US to Canada.
Unlike the earlier attempt in #272 this patch passes format validation by including all the required fields and *having them in the correct order*. Also note that the `AcceptanceDateTime` field does not accept any time with a positive timezone, this is worked around by always converting to UTC.
@Shopify/shipping 
cc @mleglise because he noted that Spree was affected
cc @eboswort because Casper is on the list of Spree users and he might have encountered this

Update USPS rates API - Fix errors

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/api_error_rate_response.xml
test/unit/carriers/usps_test.rb

When USPS changed their API the error being bubbled up was very unhelpful and not properly an active_shipping error. The reason for this is that the code for handling errors in rate response was missing a matcher for a specific type of error that was specific to a service.
@RichardBlair @kmcphillips

Handle service specific USPS rate errors more gracefully

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/us_rate_request_large.xml
test/unit/carriers/usps_test.rb

This PR fixes #275. According to the USPS documentation the container tag should not be included when the package isn't LARGE and it in fact gives an error. https://github.com/Shopify/active_shipping/pull/248 mistakenly added the container to every us to us rate request, causing them to fail.
This PR fixes a couple remote tests that failed because of this bug but nobody noticed because we don't have credentials in CI. 
I used credentials locally and ran the USPS remote tests, most are fixed, one still fails because of a different issue relating to packages with only a country (a rare case), I will fix that in a separate upcoming PR. I'll bump and release a new version after that PR.
@RichardBlair @kmcphillips cc @jnormore

Don't include container on small packages

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/world_rate_request_only_country.xml
test/unit/carriers/usps_test.rb

A failing remote test tipped me off to this. If the destination postal code was nil because only a country was provided then the API would return an error because AcceptanceDateTime is only allowed when DestinationPostalCode is present.
This PR fixes the remote test and also creates a local test for the fix.
After this and #280 are merged the USPS remote tests will all be passing and I will release a new bugfix release.
@RichardBlair @kmcphillips cc @jnormore

Fix USPS requests with only a country

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/tracking_response_alt.xml
test/remote/usps_test.rb

This PR adds a remote test for USPS tracking using a tracking number of my own which I am okay with releasing. It also fixes a bug I found in the process of actually running this remote test which is that USPS returns upper case country names, which `ActiveUtils::Country` can't find. Thus this PR adds code for finding country names in a case insensitive way.
@kmcphillips @RichardBlair

Handle upper case country names in tracking

---

README.md
lib/active_shipping/carrier.rb
lib/active_shipping/carriers/canada_post.rb
lib/active_shipping/carriers/canada_post_pws.rb
lib/active_shipping/carriers/fedex.rb
lib/active_shipping/carriers/ups.rb
lib/active_shipping/carriers/usps.rb
test/remote/canada_post_pws_test.rb
test/remote/canada_post_test.rb
test/remote/correios_test.rb
test/remote/fedex_test.rb
test/remote/kunaki_test.rb
test/remote/new_zealand_post_test.rb
test/remote/shipwire_test.rb
test/remote/stamps_test.rb
test/remote/ups_test.rb
test/unit/carriers/usps_test.rb

Certain carriers limit the address field to a certain amount of characters which cuts off the address coming from checkout when it is longer.
With this PR we'll be able to validate before that happens.
Also ```s/test:units/test:unit```
r: @trishume

Add maximum address field length to carriers

---

lib/active_shipping/carriers/ups.rb

Fixes #162 where the country code `ZZ` is sometimes returned by UPS, even though it is in the US.
@kmcphillips cc @mperham

Fix unknown country code with SUREPOST tracking

---

lib/active_shipping/carriers/ups.rb
test/fixtures/xml/ups/void_shipment_response.xml
test/remote/ups_test.rb
test/unit/carriers/ups_test.rb

This adds the ability to void UPS shipments, which is the same as canceling them. It's a good thing to do if you're not going to use a label. 
I'm wondering how the community feels about the way I set up the return values for `void_shipment`. The way I've got it, you get true if the shipment is voided and otherwise it raises an error with a message about what went wrong.
I guess I could return a response object but it seemed to me like a void shipment request is going to work 99% of the time and when it fails it's probably pretty unexpected and could merit an error rather than just a response with success? == false. 
But I'm happy to make a barebones response object if that's what y'all prefer.
Oh also, side note about the switch from `update` -> `merge`. In my fork of this repo we've …

UPS. Support for voiding shipments.

---

CHANGELOG.md
lib/active_shipping/version.rb
test/remote/canada_post_pws_test.rb
test/remote/canada_post_test.rb
test/remote/correios_test.rb
test/remote/fedex_test.rb
test/remote/kunaki_test.rb
test/remote/new_zealand_post_test.rb
test/remote/shipwire_test.rb
test/remote/stamps_test.rb
test/remote/ups_test.rb
test/unit/carriers/canada_post_pws_shipping_test.rb
test/unit/carriers/canada_post_test.rb
test/unit/carriers/correios_test.rb
test/unit/carriers/fedex_test.rb
test/unit/carriers/kunaki_test.rb
test/unit/carriers/new_zealand_post_test.rb
test/unit/carriers/shipwire_test.rb
test/unit/carriers/stamps_test.rb
test/unit/carriers/ups_test.rb

This fixes up the tests being in the wrong place from #290 and a date from #279. Also cleans up a test from #283.
Then it bumps the version number to `v1.3.0` according to semver because of the new features in this release.
This PR is mostly fixing currently broken tests in a trivial way so I'm not going to wait for review.
cc @kmcphillips

Fix tests and things up for a release.

---

README.md
Rakefile
active_shipping.gemspec
test/console.rb

This adds a console for debugging ActiveShipping code and also more importantly the APIs of the carriers. 
In the past when I'm trying to figure out something about a carrier's API I have used an IRB session with a bunch of stuff loaded and had to copy-paste a bunch of things from tests and load a bajillion files.
This PR adds a `rake console` command based on pry that has a bunch of handy things pre-defined and included:
- ActiveShipping and testing fixtures and credentials modules included
- An equivalent to the `reload!` method from 'rails console` that reloads all of the active_shipping code
- A bunch of predefined carrier objects using the local test credentials from the remote tests
- A method for pretty-printing XML strings (unfortunately too commonly needed)
@kmcphillips …

Add rake console command with handy things

---

lib/active_shipping/carriers/ups.rb

This should be all that is required to support USPS SurePost rate fetching on accounts that have a contract for it.
I can't test that this works without an account but I have some evidence from the interwebs:
- http://stackoverflow.com/questions/27231907/ups-surepost-api
- https://github.com/typefoo/node-shipping-ups/commit/08ecb7003867f3db915f267127cbfc2d80bd7a81
- https://github.com/pullingshots/Shipment/commit/5523534a6c43adef580fc78290d17af597ed49f4
@kmcphillips cc @louiskearns @shawnfrancis

Add names for UPS SurePost services

---

lib/active_shipping/carriers/fedex.rb
lib/active_shipping/errors.rb
test/fixtures/xml/fedex/tracking_response_invalid_tracking_number.xml
test/unit/carriers/fedex_test.rb

This fixes an `ArgumentError` on `ResponseContentError` initialization when trying to parse tracking response from FedEx.
The existent code for FedEx's `parse_tracking_response` raising `ResponseContentError` error when tracking details notification is an `ERROR` with code different from `9040`. But it provides only one argument for initialization when two expected.
Backtrace:
```
ArgumentError: wrong number of arguments (1 for 2)
/active_shipping-1.3.0/lib/active_shipping/errors.rb:19:in `initialize'
/active_shipping-1.3.0/lib/active_shipping/carriers/fedex.rb:578:in `exception'
/active_shipping-1.3.0/lib/active_shipping/carriers/fedex.rb:578:in `raise'
/active_shipping-1.3.0/lib/active_shipping/carriers/fedex.rb:578:in `parse_tracking_response' …
```

[FedEx] Fix ArgumentError on parse tracking response.

---

lib/active_shipping/carriers/fedex.rb
test/fixtures/xml/fedex/tracking_response_empty_status_detail.xml
test/fixtures/xml/fedex/tracking_response_invalid_status_code.xml
test/unit/carriers/fedex_test.rb

It allows to rescue situations where status detail has no code when trying to parse tracking info from FedEx.
Backtrace:
```
NoMethodError: undefined method `text' for nil:NilClass
/active_shipping-1.4.0/lib/active_shipping/carriers/fedex.rb:588 in parse_tracking_response
/active_shipping-1.4.0/lib/active_shipping/carriers/fedex.rb:161 in find_tracking_info
```

[FedEx] Raise an error on invalid status code in response.

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/tracking_response_batch.xml
test/unit/carriers/usps_test.rb

An XPath that was designed without the idea of batched responses was giving back all the errors in a batch tracking request concatenated together instead of a specific error. This fixes the XPath and tests it.
@kmcphillips @garethson

Fix bug with batch tracking errors

---

lib/active_shipping/carriers/usps.rb
test/fixtures/xml/usps/tracking_response_alt.xml
test/unit/carriers/usps_test.rb

While running batch processing on tracking numbers I discovered a few bugs in active_shipping USPS tracking. This PR fixes two of them:
- Some country names aren't the same as they are in ActiveUtils and have to be mapped separately. I only found 2 out of the 6000 numbers I tested but I have emailed someone at USPS asking if they have a full list.
- One type of event ("Origin Post is Preparing Shipment") doesn't have a time, even though it really should. This currently causes an exception. I handled this by returning an arbitrary date in the past (Jan 1, 2000).
I'm definitely open to discussion on how I handled the lack of date. I imagine lots of code would assume that all events have a time, which is true for everything except this rare event type, which is why I still return a time …

Fix bugs in USPS tracking

---

lib/active_shipping/carriers/fedex.rb

That was causing an error when doing:
`ActiveShipping::FedEx.logger = Logger.new($stdout)`

Remove reference to undefined variable if using FedEx logger.

---

lib/active_shipping/carriers/usps.rb

The `OriginZip` xml element (added for the May 31, 2015 USPS Web Tools API update) was out of order in comparison to the Commercial flags, causing the request to fail. This change simply corrects the parameter order to match the USPS API docs.
https://www.usps.com/business/web-tools-apis/rate-calculator-api.htm
Fixes #303

Fix USPS international prices for Commercial Base and Commercial Plus.

---

lib/active_shipping/carriers/usps.rb
test/remote/usps_test.rb

USPS changed their testing server, at least for insecure tracking (not sure about the others).
This fixes the error `API Disabled: TrackV2.  This test request is no longer valid. Please use http://stg-production.shippingapis.com/ShippingAPI.dll` when running tests.
The thing is the new test server can't find any of the production tracking numbers that we use for testing and I can't find any tracking numbers that work on the server. So we now use the production server for the remote tracking tests, which since it is just tracking shouldn't be a big deal.
@kmcphillips

Use new USPS staging server, and don't use it

---

test/remote/fedex_test.rb

Moves to more robust test tracking numbers that won't change every time FedEx deploys their code.
@kmcphillips

Fix fedex remote tests

---

lib/active_shipping/rate_estimate.rb
test/unit/rate_estimate_test.rb

Some shipping rates require a phone number.
Add phone required to the shipping estimate.
Review: @kmcphillips @mdking 
cc: @jnormore

add phone required to rate estimate

---

test/remote/correios_test.rb

A Correios remote test is failing because the service is unavailable for the informed route. Skip it for now.
@kmcphillips @RichardBlair

Skip remote Correios test, service unavailable for the informed route.

---

active_shipping.gemspec

Bump active_utils dependency to v3.1.0
Diff for active_utils https://github.com/Shopify/active_utils/compare/v3.0.0...v3.1.0
Review @kmcphillips @RichardBlair

Bump active_utils to v3.1.0

---

CHANGELOG.md
active_shipping.gemspec

Differences from 3.1.0 to 3.2.0: https://github.com/Shopify/active_utils/compare/v3.1.0...v3.2.0
@RichardBlair @garethson @mdking

Bump active_utils to 3.2.0

---

lib/active_shipping/carriers/fedex.rb
test/remote/canada_post_pws_test.rb
test/remote/fedex_test.rb
test/unit/carriers/fedex_test.rb

`ShipmentEvents` for FedEx weren't initialized with their `<EventType>`s. This results in no status code being associated with a `ShipmentEvent`.
Save the `<EventType>` , much like we do with [USPS `ShipmentEvents`.](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/usps.rb#L254)
Review: @mdking @lucasuyezu @cyprusad

Include event type codes for FedEx tracking events

---

lib/active_shipping/carriers/fedex.rb
lib/active_shipping/carriers/usps.rb
test/unit/carriers/fedex_test.rb

- use a different business days calculator
- option for absolute "pickup_date" instead of relative "turn_around_time"

Fedex "Home Delivery" is Tues-Sat

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb
test/test_helper.rb

- Create a return label by setting the return_service_code
- list of return service codes for reference
- units used are now always based on shipper's country,
allows international return from a different country than shipper
- don't include SoldTo when it's a return
- return requires a description at the package level

Ability to create a UPS return label

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb
test/test_helper.rb

Adds the `DryIce` node to the purchase request when the packages have a `dry_ice` option.
Usage looks like:
```ruby
Package.new(80, [2, 6, 12], :units => :imperial, :dry_ice => {weight: 1.4})
```
and gets you a nice comment on the label
and I'm hoping to use the same `dry_ice` hash option for FedEx soon.

Add ability to ship dry ice to UPS

---

lib/active_shipping/carriers/usps.rb
lib/active_shipping/tracking_response.rb
test/remote/usps_test.rb

We had a requirement to determine the first delivery attempt on a shipment as opposed to the actual delivery date.
For USPS, we pull the first event which is a failed delivery attempt.

Added support for USPS attempted delivery dates

---

README.md

Improve README's code readability by:
* Using markdown's ruby syntax highlighting 
* Making code example follow **code style guide** (present on CONTRIBUTING.md)
* Use 2 space indent, no tabs.
* No spaces after `(`, `[` and before `]`, `)`
* Using new hash syntax

Improve README's code readability

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb

Which occurs when one or more packages' value is nil.
Should fix https://github.com/Shopify/active_shipping/issues/341
If no packages have a value, then the entire block is
avoided to avoid an accidental 0 value. According to the
docs, `InvoiceLineTotal` is only required for "International
non-document shipments."

Avoid exception during delivery date request

---

README.md

I spent too much of my life figuring out that login keys were not the same between active_shipping and FedEx. I assume I'm not the first to experience this problem. Hopefully this documentation note will help others.

Document FedEx login and test keys

---

lib/active_shipping/carriers/fedex.rb
test/fixtures/xml/fedex/tracking_response_failure_code_9045.xml
test/unit/carriers/fedex_test.rb

I'm not sure of the source of this failure. I accidentally left a 6 second interval polling task open in a terminal for most of the day to the FedEx test endpoint, so maybe FedEx cut me off. It's also possible their test service is not functioning correctly at the moment. At any rate, it's better to handle the code because the error message and class which were returned to me weren't helpful.
If we don't handle this error, we get:
```
ActiveShipping::Error: Tracking response does not contain status code
```
If we do handle this error, we get:
```
ActiveShipping::ResponseContentError: Sorry, we are unable to process your tracking request.  Please retry later, or contact Customer Service at 1.800.Go.FedEx(R) 800.463.3339.
```
I dumped the response xml from a pry session to use as a test …

Handle FedEx tracking response failure code 9045

---

.gitignore
dev.yml

@garethson @jonathankwok @RichardBlair 
cc @burke 
Adds support for Shopify's `dev-up` to this gem. Supports:
* `dev cd active_shipping`
* `dev up`
* `dev test`
* etc.

Add dev.yml

---

dev.yml
test/unit/carriers/usps_test.rb

@thegedge @garethson @jonathankwok 
Continuing work on getting the build green. :green_heart: 
Fixes `dev test test/file.rb` running an individual file.
Fixes leaky test which would fail on non UTC running locally
```
~/source/active_shipping(dev-test ✗) dev test test/unit/carriers/usps_test.rb
Run options: --seed 14038
.......................F.......................
Finished tests in 0.852873s, 55.1079 tests/s, 155.9435 assertions/s.
1) Failure:
USPSTest#test_find_tracking_info_should_handle_special_cases [test/unit/carriers/usps_test.rb:143]:
Expected: 2000-01-01 00:00:00 -0500
Actual: 2000-01-01 00:00:00 UTC
```

Fix dev test and leaky timezone test

---

lib/active_shipping/carriers/ups.rb

@garethson @jonathankwok @thegedge 
Get this damn build :green_heart: again.
We got this warning a while back:
Our servers and environment default to the proper TLS version, but TravisCI is not apparently. So we are forcing `:TLSv1_2` and that gets our build passing again.

Force TLS 1.2 for UPS

---

lib/active_shipping/carriers/usps.rb
test/unit/carriers/usps_test.rb

Noticed that if we don't get an EventTime in the response we return arbitrary date in the past (1/1/2000). This is a little bit confusing, it would be clearer to return something that would clearly signal that the EventTime is missing, so I'm going with Time.at(0).
Thoughts?
cc/ @kmcphillips @jonathankwok @cyprusad

Change the returned arbitrary date to epoch

---

test/remote/usps_test.rb

Taking out a flakey test that fails because tools.usps.com can't give tracking information for a shipment once its handed to canada post.
Besides the test directly below it more or less tests the same thing.
cc/ @mdking @lucasuyezu @thegedge

Removed flakey test

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb
test/test_helper.rb

Fixes #52 
Adds an optional `:insured_value` option to packages for use with UPS.

Add InsuredValue option for UPS packages

---

test/remote/ups_test.rb

Time zone shiftiness going on:
```
[1] pry(main)> Date.today
=> Tue, 26 Apr 2016
[2] pry(main)> 3.business_days.from_now
=> 2016-05-02 09:00:00 +0000
[3] pry(main)> 3.business_days.after(Date.today)
=> Fri, 29 Apr 2016
```
`from_now` just adds the n days, whereas `.after` takes into account [business hours](https://github.com/bokmann/business_time/blob/develop/lib/business_time/business_days.rb#L28), adding an extra day if the present time is past business hours (which is why it's flaky right now, since most of the time we're running our builds outside of business hours for the system (UTC)).
Carrier responses take into account business time and rolling forward, so we should too in our tests.
Fixes half of the red build - the other half is fixed by …

Take into account business hours for UPS delivery estimates

---

lib/active_shipping/carriers/usps.rb
test/remote/usps_test.rb

There are multiple possible `attempted_delivery` codes - see page 335 of [this](https://ribbs.usps.gov/intelligentmail_package/documents/tech_guides/PUB199IMPBImpGuide.pdf), or look at this screenshot:
There are multiple codes for "Notice Left"/Attempted Delivery - rather than just use code 55, use all of the ones in the appendix. Code H0 came from me finding responses manually through a database of tracking codes, seems to also be Attempted Delivery (unsurprisingly not documented).
Add an array of known `ATTEMPTED_DELIVERY_CODES` and check for inclusion when saving the `attempted_delivery_date`.
This fixes part of the red build, which doesn't actually depend on this fix - it was just an outdated tracking number. The other half is fixed by …

Use multiple attempted delivery codes for USPS tracking

---

lib/active_shipping/carriers/canada_post_pws.rb

Per the Canada Post documentation, tracking-pin may not be present in the non-contract-shipping-info response.  Currently that case is resulting in an exception.

Canada Post PWS fix for missing tracking-pin (optional field)

---

lib/active_shipping/carriers/ups.rb
test/unit/carriers/ups_test.rb

For the other carrier adapters, we always save something for the `message` of a `ShipmentEvent` - 
- [USPS does it here, storing the event's `Event` in `message`](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/usps.rb#L627)
- [FedEx also does it here, saving `EventDescription`](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/fedex.rb#L664)
- [Canada Post saves the `event-description` in `message`](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/canada_post_pws.rb#L328)
UPS doesn't do anything, and just [gives it a `nil` value](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/ups.rb#L853). Rather than `nil` the value, we can do what USPS and FedEx …

Save description for UPS shipment event in message

---

lib/active_shipping/carriers/ups.rb

Errors from UPS were getting thrown as runtime errors which are harder to catch. This change mirrors how [errors are thrown in the FedEx carrier](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/fedex.rb#L606).

Add ResponseContentError for raised UPS error

---

lib/active_shipping/carriers/ups.rb
test/remote/ups_test.rb
test/unit/carriers/ups_test.rb

This adds the ability to bill duties and taxes to a third party shipping account.
Also contained in this PR is a change to actually use parameter `negotiated_rates` which was already documented above the `create_shipment` method definition. We were inferring that based on the presence of an `origin_account` but given that negotiated rates are based on who's paying, the existence of third party billing means it doesn't really make sense to do that. However this could be a breaking change for anyone relying on the `origin_account` to automatically turn on negotiated rates.
Really I think we should probably rename `origin_account` to be `shipper_account` since that's a better description of what it is.

UPS. Ability to Bill Third Party for Duties and Taxes

---

dev.yml

@jonathankwok @thegedge 
```
~/source/active_shipping(master ✔) dev up
🦄  the build: true option for ruby in dev.yml is obsolete and no longer has any effect.
✓ 1/2: Installing Ruby (nothing to do)
✓ 2/2: Running Bundler (nothing to do)
```

Remove build: true from ruby

---

dev.yml

Specified homebrew's 2.2.5 version in dev.yml so `dev` commands work again.
cc: @jonathankwok @MalazAlamir

specify homebrew 2.2.5 package as the default dev ruby version

---

lib/active_shipping/carriers/fedex.rb
test/unit/carriers/fedex_test.rb

Currently, a hard coded value of 'PAPER_7X4.75' is supplied for every package label. The FedEx WebServices Developers Guide says:
```
When using an ImageType of PDF or PNG, these values display a thermal format label:
PAPER_4X6
PAPER_4X8
PAPER_4X9
these values display a plain paper format shipping label:
PAPER_7X4.75
PAPER_8.5X11_BOTTOM_HALF_LABEL
PAPER_8.5X11_TOP_HALF_LABEL
```
I've allowed for the default (no option specified) to retain the current functionality. In other words, 'PAPER_7X4.75' will be used without a specified option.
In addition to the automated tests, I've manually tested with 'PAPER_4X6' (what I need for a thermal printer)
Sample use:
```
carrier.create_shipment(location_1, location_2, [package], test: true, label_stock_type: 'PAPER_4X6')
```

Allow for optional FedEx package label stock type (label dimensions)

---

lib/active_shipping/carrier.rb

We need to add cancel_shipment to the interface. Will create an issue to come back and add in actual functionality to all carriers we have implemented.
I think this is everything I need to get started. Let me know if you have any other context that I'm missing
@jonathankwok @RichardBlair @mdking @garethson @kmcphillips

Add cancel_shipment to the interface

---

README.md
lib/active_shipping/carriers.rb
lib/active_shipping/carriers/australia_post.rb
test/credentials.yml
test/fixtures/json/australia_post/calculate_domestic.json
test/fixtures/json/australia_post/calculate_domestic_2.json
test/fixtures/json/australia_post/calculate_international.json
test/fixtures/json/australia_post/calculate_international_2.json
test/fixtures/json/australia_post/error_message.json
test/fixtures/json/australia_post/service_domestic.json
test/fixtures/json/australia_post/service_domestic_2.json
test/fixtures/json/australia_post/service_international.json
test/fixtures/json/australia_post/service_international_2.json
test/remote/australia_post_test.rb
test/test_helper.rb
test/unit/carriers/australia_post_test.rb

Support currently:
- Parcel service for domestic and international
- Parcel calculate for domestic and international

Add AustraliaPost Carrier

---

lib/active_shipping/rate_estimate.rb
test/unit/rate_estimate_test.rb

Adds a delivery category to RateEstimate. Can be used to add generic classification to our rate types.
@kmcphillips @jonathankwok

Adds delivery_category to RateEstimate

---

lib/active_shipping/response.rb
test/unit/response_test.rb

Having this class raise on initialize if `success` is `false` is a huge pain. Allow an option to safely change the behaviour for users who do not want the raise behaviour while still supporting the existing behaviour.
Review @RichardBlair @lucasuyezu @jonathankwok

Allow a failed response not to raise

---

test/unit/carrier_test.rb

@garethson @jonathankwok 
Related to #381
Digging into getting Rails 5 support. We have failing tests around date offsets on the branch. I found the `Carrier` base class had no tests, and I think the bug may be in one of the methods in this class.
Adding tests.
Build is _probably_ going to be red as surrounding the US holiday a bunch of delivery times on the remote tests are wrong. 🇺🇸 🎆

Add test for base Carrier class

---

test/unit/carriers/shipwire_test.rb
test/unit/rate_estimate_test.rb

@garethson @jonathankwok 
Related to #381 and follows #383. 
Our Rails 5 test failures are all involved in date arithmetic and Shipwire. This does a few things to clean up how we test dates and delivery estimates to continue to narrow in on the problem.

Shipwire delivery date test cleanup

---

lib/active_shipping/carrier.rb
test/unit/carrier_test.rb

@garethson @jonathankwok 
Works toward #381. Our test failures in Rails 5 are around date math, and the `Time` vs `DateTime` calculations.
This fixes assumptions about class, and cleans up some really awkward ruby syntax. Tests the weekend cases too.

Correctly offset days for business days

---

.travis.yml
Gemfile.activesupport50
active_shipping.gemspec
test/unit/carriers/ups_test.rb

@garethson @jonathankwok 
cc @Sk8withaguitar @chaserx 
Closes #381 
Adds support for Rails 5.
In #383 #384 #385 I cleaned up some tests and date problems. This fixes a couple more small date math issues. Mainly it adds tests for Rails 5 and depends on the https://github.com/Shopify/active_utils/pull/69 release.
I'll do a gem release once this is merged.

Rails 5 support

---

lib/active_shipping/carriers/canada_post_pws.rb
test/unit/carriers/canada_post_pws_rating_test.rb

Add a cattr_reader to access the @@name variable provided by the class.
This is something standard in the other carriers that is missing from Canada Post Pws.

Add accessor for CanadaPostPWS @@name

---

lib/active_shipping/rate_estimate.rb

There is currently no attribute in `RateEstimate` that allows for OPTIONAL priced options.
Allow for an attribute `shipment_options` to be initialized in `RateEstimate` that can be an `Array` of objects `{ code: String, price: Integer }`. 
Review: @kmcphillips @lucasuyezu

Added shipment_options attribute to RateEstimate

---

CHANGELOG.md
lib/active_shipping/carriers/fedex.rb
test/remote/fedex_test.rb
test/remote/kunaki_test.rb
test/unit/carriers/fedex_test.rb

Simple fix with tests to enable specifying what format a generated label should be returned in via the FedEx API.
As a side-note, what the hell is going on with the changelog file - where are the changes for version 1.6.2 until now?  What's up with all the remote test failures in the test suite?

Support various FedEx label formats - issue #392

---

lib/active_shipping/rate_estimate.rb
test/unit/rate_estimate_test.rb

This adds a description field to rate estimates so that carriers
can better describe provided rates. API Carriers already support this within Shopify,
but I believe the API should be the same across the board.

Add description to rate estimates

---

test/unit/carriers/canada_post_pws_register_test.rb
test/unit/carriers/ups_test.rb

We have two cases of old tests where we say `assert` where we mean `assert_equal`. The API of MiniTest's assertion is confusing, as the second argument is a description message. So these both false passed.

Change assert to assert_equal

---

README.md

I added links to several of the files mentioned in the README so that it's easy to access the mentioned files. I also turned the plaintext URL's into links so that they can be clicked on the [shopify.github.io](http://shopify.github.io/active_shipping/) page.

[ci-skip] Add links to README.md

---

test/unit/carrier_test.rb
test/unit/carriers/fedex_test.rb
test/unit/carriers/shipwire_test.rb
test/unit/rate_estimate_test.rb
test/unit/shipment_event_test.rb
test/unit/tracking_response_test.rb

**_This pull request is opened for conversation and direction on the best way to resolve the issue._**
When running the tests locally, I had two tests fail due to an issue
with Timecop. A [similar issue](https://github.com/travisjeffery/timecop/issues/100) has been opened on Timecop's repo, but it has not been addressed. Here are the errors:
```
Finished in 12.098837s, 45.0457 runs/s, 126.1278 assertions/s.
1) Failure:
FedExTest#test_delivery_date_from_ground_home_transit_time [/home/alex/fn/active_shipping/test/unit/carriers/fedex_test.rb:292]:
--- expected
+++ actual
@@ -1 +1 @@
-Mon, 08 Jun 2015
+Sat, 06 Jun 2015 00:00:00 +0000
2) Failure:
FedExTest#test_turn_around_time_default [/home/alex/fn/active_shipping/test/unit/carriers/fedex_test.rb:54]:
--- expected
+++ actual
@@ -1 +1 @@ …
```

Update Timecop dates to bypass weird test bug

---

lib/active_shipping/carriers/ups.rb
test/unit/carriers/ups_test.rb

We were encountering `REXML::ParseException` on [this line, where we call `Hash.from_xml(response)`](https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/carriers/ups.rb#L889) when the `response` contains a "UTF-8, but not actually" character (in our case, `\xCF`). This means the response we're getting is assumed to be UTF-8 but isn't necessarily encoded in UTF-8, for example in the case of UPS, it's ISO-8859-1.
[The typical fix for an encoding issue like this is to re-encode the string in what we want it to actually be, in this case UTF-8.](http://www.justinweiss.com/articles/3-steps-to-fix-encoding-problems-in-ruby/), so this PR will re-encode everything into UTF-8; a no-op if it's properly encoded in UTF-8 and a fix for the exceptional cases.
@kmcphillips …

Force re-encoding of ISO-8859-1 to UTF-8

---

lib/active_shipping/rate_estimate.rb
test/unit/rate_estimate_test.rb

Currently there is no way to detect which services provide included features, like insurance and tracking. There is `shipment_options` but these are used for options that the merchant might select on top of the included ones.
Add a new attribute `price_details` that can be initialized with detailed informations on each item of a rate estimate.
@kmcphillips @jonathankwok @mdking

Add price_details attribute to RateEstimate

---

lib/active_shipping/carriers/ups.rb

From their documentation
From their documentation
```xml
<Status>
<StatusType>
<Code>I</Code>
</StatusType>
<StatusCode>
<Code>DS</Code>
</StatusCode>
</Status>
```
Something they actually returned.
@mdking @RichardBlair

Handle a potential missing 'required' UPS element in TrackResponse

---

lib/active_shipping/rate_estimate.rb
lib/active_shipping/rate_response.rb

Fix some typos in documentation for RateResponse & RateEstimate. Also
make minor cosmetic doc changes for consistency.

[ci skip] Fix documentation typos

---

lib/active_shipping/carriers/ups.rb
test/fixtures/xml/ups/no_status_node_success.xml
test/unit/carriers/ups_test.rb

Some `TrackResponse`s from UPS don't have a status node, but are considered "Successful" responses. The current implementation expects all successful responses to have a status node but that's not true in all cases - the XML fixture I added is a real-world example of a response that has no status node but is considered a successful response.
This PR prevents the `status_code.at('Code').text` from failing on the `.text` call by not reading through the non-existent status nodes. 
What this means is that at the end when building `TrackingResponse`, the `@status` field will be empty; this is preferable to raising without returning anything so this is an acceptable side-effect.
@benwah @thegedge @iWuzHere

Handle UPS tracking responses with no status code

---

lib/active_shipping/carriers/fedex.rb
test/fixtures/xml/fedex/tracking_response_failure_code_9080.xml
test/unit/carriers/fedex_test.rb

Resource: https://www.fedex.com/us/developer/WebHelp/ws/2014/dvg/WS_DVG_WebHelp/index.htm#Appendix_O_Error_Code_Messages.htm
Error codes are more extensive than known in FedEx, and for some errors, they were continuing past the error code check because they weren't known in the `case`. From the resource, I sorted the tracking errors (9xxx) between transient and non-transient, on the basis of whether the message contains "`Please retry later`" or not. 
This strategy aligns with what I've seen with existing numbers (e.g. 9080 is the error returned when I tried to track something with code `BadTrackingCode`, and the error response doesn't prompt a retry.)
As for the error classes being returned, I'm maintaining the current return pattern; `ShipmentNotFound` for transient errors, and …

Sort FedEx tracking response error codes between retryable and not

---

.travis.yml
gemfiles/activesupport32.gemfile
gemfiles/activesupport40.gemfile
gemfiles/activesupport41.gemfile
gemfiles/activesupport42.gemfile
gemfiles/activesupport50.gemfile
gemfiles/activesupport_master.gemfile

@thegedge @jonathankwok 
Functional noop.
Moves the gemfiles into a folder structure, and with the `.gemfile` extension which most editors and things understand better. Just code quality and readability cleanup.

Use gemfiles/*.gemfile structure

---

test/remote/ups_test.rb

UPS remote test fails on the weekend.
One was not taking weekends into account at all. The other appears to be an exception around next day showing up on the Monday, not the Tuesday. Less confident about that one, but can't test it until the week anyway.
@jonathankwok @mdking @thegedge

Fix UPS remote tests on weekends

---

Rakefile
lib/active_shipping/carriers/canada_post_pws.rb
test/remote/fedex_test.rb
test/unit/carriers/canada_post_pws_tracking_test.rb
test/unit/carriers/fedex_test.rb
test/unit/carriers/kunaki_test.rb
test/unit/carriers/stamps_test.rb
test/unit/carriers/usps_test.rb
test/unit/external_return_label_request_test.rb

Test output is polluted with so many warnings.
This reduces the extra verbose mode, and fixes a bunch of the ones that were still logged.

Clean up test output and fix warnings

---

CONTRIBUTING.md
MIT-LICENSE
README.md
active_shipping.gemspec
lib/active_shipping.rb
test/test_helper.rb

@jonathankwok @mdking @thegedge 
Moving around documentation and getting it up to date. Removing references to Jaded Pixel. Setting expectations for contribution. Getting everything more consistent and cleaned up.
Bonus: Forgot to require pry in test.

Cleanup README and docs and metadata

---

.travis.yml
active_shipping.gemspec
gemfiles/activesupport32.gemfile
gemfiles/activesupport40.gemfile
gemfiles/activesupport41.gemfile

For version 2.0, we are dropping support for any rails version that is no longer maintained.
Closes #426
@thegedge @mdking @jonathankwok

Drop support for Rails below 4.2

---

lib/active_shipping/carriers/correios.rb
lib/active_shipping/carriers/ups.rb
lib/active_shipping/carriers/usps.rb
lib/active_shipping/external_return_label_request.rb
test/remote/canada_post_pws_platform_test.rb
test/unit/carriers/correios_test.rb

@thegedge @mdking @jonathankwok 
These UTF-8 encoding strings are no longer necessary as this is the default in ruby now.

UTF-8 by default so comments no longer needed

---

lib/active_shipping/carriers/australia_post.rb
lib/active_shipping/carriers/new_zealand_post.rb

These come in as part of the `require 'actives_support/all'`  which is line 1 of `active_shipping.rb`
@jonathankwok @mdking @thegedge

Required as part of activesupport/all

---

active_shipping.gemspec
test/test_helper.rb

Let's use `minitest-reporters` gem to give a cleaner output from tests, inline with most of our other apps too.
@jonathankwok @mdking @thegedge

Use minitest-reporters gem for nicer output

---

test/test_helper.rb

Reduce some of the noise locally, making it easier to red/green/refactor and unit test.
This suppresses the detailed output of skips locally, but still shows them in CI output.

Do not show detals of skips locally

---

test/unit/carrier_test.rb
test/unit/carriers_test.rb
test/unit/external_return_label_request_test.rb

Now that #442 is in I'm going to slowly start converting the fragile, confusing, and unclear `def test_` DSL and replace it with the `ActiveSupport::TestCase` `test()` block based DSL.
Changes are just around naming and formatting mostly. Split up test cases that do more than one thing onto distinct tests with a clearer fail message. Extracted some shared variables. In one case I replaced `assert_silent` with `assert_nothing_raised` because the original author I don't think understood the assertions. The former is about printing to standard out, but I'm sure they intended to deal with exceptions.
This does `Carrier` `Carriers` and `ExternalReturnLabelRequest`.

Modernize tests - Part 1

---

lib/active_shipping/location.rb
test/unit/location_test.rb

All cleanup in `Location`.
No functional change. Cleans up formatting, extracts a constant, removes old hash syntax, expands methods to be more consistent.
Reformats the tests to be `test "" do` and adds a bunch of missed coverage.

Clean up tests and formatting for Location

---

lib/active_shipping/carriers/fedex.rb
test/unit/carriers/fedex_test.rb

Attempting to pass multiple reference elements to a fedex label currently generates an invalid format error.
The generated XML looks like this
```
<CustomerReferences>
<CustomerReferenceType>TYPE_1</CustomerReferenceType>
<Value>Val1</Value>
<CustomerReferenceType>TYPE_2</CustomerReferenceType>
<Value>Val2</Value>
</CustomerReferences>
```
This fix simply corrects the format to
```
<CustomerReferences>
<CustomerReferenceType>TYPE_1</CustomerReferenceType>
<Value>Val1</Value>
</CustomerReferences>
<CustomerReferences>
<CustomerReferenceType>TYPE_2</CustomerReferenceType>
<Value>Val2</Value>
</CustomerReferences>
```
I've modified the create_shipment test to include two refs and test them.

Fix CustomerReference element nesting for FedEx labels with multiple refs

---

test/helpers/holiday_helpers.rb
test/remote/ups_test.rb
test/test_helper.rb

This allows us to wrap assertions around `with_holidays(:carrier)` - And lets us support other carriers such as usps, fedex in the future.
FedEX will be more complicated to support: http://www.fedex.com/us/service-guide/holiday-schedule.html
USPS pretty simple: https://about.usps.com/news/events-calendar/2016-postal-holidays.htm

Added support for Holiday customization in tests

---

lib/active_shipping/rate_estimate.rb
test/unit/carriers/canada_post_test.rb

I believe this method is the source of a tricky bug in my application, and I suspect it is in others as well.
I discovered it while inspecting API responses from Stamps.com. As indicated by the method signature, API responses are expected to provide _calendar_ date information – any timezone information is discarded here, which is correct. However, the `#date_for` method returns an instance of DateTime, which includes time zone information. In this case that time zone is set to the default value of UTC (+0000) which is likely not correct.
If the resulting value is passed, for instance, to a Rails app that saves it in a timestamp field, it will be erroneously converted to a local time thus possibly changing the date (as it does in my application).
Changing this method to return a Date …

#date_for should return a Date, not a DateTime

---

.travis.yml
test/unit/carriers/new_zealand_post_test.rb

Ruby 2.4 has some behaviour changes, most notable the `Integer` class combining `Fixnum` and `Bignum`:
https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/
This adds it to CI. 
Related to #453. cc @ddrmanxbxfr

Add Ruby 2.4.0 to CI

---

test/helpers/holiday_helpers.rb

This PR adds a basic holiday configuration for the 2017 year on the ups provider for tests.
Required for #453 and further PR that will be done in 2017.

Added holiday configuration for 2017 on ups provider

---

lib/active_shipping/package.rb
test/remote/fedex_test.rb
test/remote/stamps_test.rb
test/remote/ups_test.rb
test/remote/usps_test.rb
test/unit/carriers/canada_post_test.rb
test/unit/carriers/fedex_test.rb

In ruby 2.4, Fixnum and Bignums were unified together into the Integer class.
We should deprecate them so that we can upgrade to ruby 2.4 without deprecations.
Links related to this change in ruby...
https://bugs.ruby-lang.org/issues/12005
http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

Deprecate Fixnum usage for Integer (Ruby 2.4 Compatibility)

---

test/unit/package_item_test.rb

Pretty simple change. This modernizes the tests for `PackageItem`. But I rewrote these tests recently as this was all untested. So it's in pretty good shape. Just changing to the block syntax now that we don't support old versions. All part of 2.0.

Modernize PackageItemTest

---

test/unit/package_test.rb

Simple clean up of `PackageTest` to more modern syntax. Messaging changed only. Again, a file I wrote and cleaned up very recently so the contents of the tests is pretty solid.

Modernize PackageTest

---

test/unit/response_test.rb

1. Uses `test "" do` syntax.
2. Multi-line `.new` because readability and line length considerations.
3. `assert_predicate` over `assert`.

Modernize ResponseTest

---

active_shipping.gemspec
test/test_helper.rb

Mostly a setup PR.  Adds the `vcr` and `webmock` dependencies so we can run remote tests locally, and push the results to CI.
Before I merge I'll try running some carrier tests to verify the saved cassette data doesn't contain credentials 😅

Add VCR gem for remote tests

---

lib/active_shipping/carriers/fedex.rb
test/fixtures/xml/fedex/tracking_response_no_results.xml
test/fixtures/xml/fedex/tracking_response_unable_to_process.xml
test/remote/fedex_test.rb
test/unit/carriers/fedex_test.rb

In a couple of places we were raising an `ActiveShipping::Error` when we could raise/return a more informed `ActiveShipping::TrackingResponse(false, ...)` that has additional information (e..g, response, request) for clients of this gem.
The one point of discussion here is w.r.t. the semantics of `ResponseError`. Generally it means there was an issue in the response, but for these two cases I've changed aren't considered error responses by FedEx, and aren't given special status codes (i.e., `/TrackReply/Notifications/Code` is 0), so perhaps this doesn't make sense?
Also made a few small formatting changes on nearby code (separate commit).

Raise a ResponseError for FedEx#find_tracking_info

---

lib/active_shipping/carrier.rb
test/unit/carrier_test.rb

Carriers implement different ways to define what services are available for a route. We should have a common interface to fetch this information.
By adding `available_services` method to the `Carrier` class, we could easily fetch a list of available services between two countries.
Other things to consider: There's a few other things that could impact the service availability like package price and weight (and many more). I figured the most common would be by route (countries from and to) and if you have a package, you can always just fetch the rates to see the available services.
I'm also not sure about the input parameters, using countries seems simple enough and to integrate well with carriers but we could also use a full `Location` to represent the origin and destination.
cc @qq99 …

Add available_services method to carrier class

---

lib/active_shipping/shipment_packer.rb
test/unit/shipment_packer_test.rb

There's currently an issue with `ShipmentPacker#pack` when max weight is passed in as a float. 
https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping/shipment_packer.rb#L49
Particularly `(maximum_weight - package_weight) / item[:grams].to_i`
if max weights is a float (or something like it) they'd be off by one package.. this is because it tries to pack as much as it can in one box, so if they pass a float for `maximum_weight ` we can end up packing half an item
````
irb(main):001:0> 1.0 / 2
=> 0.5
irb(main):002:0> 1 / 2
=> 0
irb(main):003:0> 
````
Which then `items.reject! { |i| i[:quantity].to_i==0 }` discards the remaining half of the item.
Solution is to `.to_i` the numerator, denominator is already an integer.

Fix ShipmentPacker#pack to pack whole items when max weight is float

---

lib/active_shipping/shipment_packer.rb
test/unit/shipment_packer_test.rb

Just splitting out some of the work from https://github.com/Shopify/active_shipping/pull/484
Here I'm just renaming methods, using `test "blabla" do` syntax for tests, and changing hash rocket to colon syntax.
suggested in: https://github.com/Shopify/active_shipping/pull/484#discussion_r101571037

Further improve shipment packer and tests

---

lib/active_shipping/shipment_packer.rb
test/unit/shipment_packer_test.rb

The current ExcessPackageQuantity error is checked using:
`total_weight > (maximum_weight * EXCESS_PACKAGE_QUANTITY_THRESHOLD)`
This works for the most part, but this starts to fail when packages are not packed to their max capacity. For example, max weight is 750g, you have one item that weighs 500g with 10001 quantity, the check will do (500 * 10001) > (750 * 10000), which returns false. But at the end of the packing process, you would still end up with 10001 packages, which is over the threshold.
I think this validation is still good, but its not 100% accurate, its a best guess, looser validation. If it returns true, then you will definitely end up with packages over the allowed threshold. But it can miss the case I mentioned above. 
I decided to keep this validation there, to short …

Fix ExcessPackageQuantity validation

---

lib/active_shipping/carriers/usps.rb
test/unit/carriers/usps_test.rb

SSLv3 will no longer be supported by USPS Web Tools after March 24 2017.
> As of approximately 5:00 PM ET on February 13, SSLv3 support has been discontinued in the Web Tools CAT/external testing environment (https://stg-secure.shippingapis.com/shippingapi.dll)
>Effective March 24, 2017, Web Tools will discontinue support of SSLv3 for securing connections to our HTTPS APIs including but not limited to all shipping label and package pickup APIs. After this change, integrations leveraging SSLv3 will fail when attempting to access the APIs.
This PR explicitly sets the `ssl_version` for USPS to `:TLSv1_2`.  
However, tests are still passing in the external testing environment (which would fail with SSLv3 after Feb 13) even without explicitly setting the `ssl_version`.
`ActiveUtils` uses …

explicitly set USPS ssl_version to TLSv1_2

---

lib/active_shipping/carriers/usps.rb
test/test_helper.rb
test/unit/carriers/usps_test.rb

This PR truncates origin +4 zip codes for USPS world rate requests using the `strip_zip` method.
`build_world_rate_request` may throw an invalid zip code error if a +4 origin zip code is used in its original form. `build_us_rate_request` gets around this by calling `strip_zip` on any zip codes passed into the XML for cleansing. I'm adding the same behaviour to the `build_world_rate_request` method when it creates its own `xml`.

Strip 9 digit origin zip code for world rate requests

---

active_shipping.gemspec
gemfiles/activesupport50.gemfile

Bumping active_utils dependency to `~> 3.3.0`, to support changes implemented on https://github.com/Shopify/active_utils/pull/78 and https://github.com/Shopify/active_utils/pull/79.

Bump active_utils dependency to 3.3.0

---

CHANGELOG.md
lib/active_shipping/version.rb

Bumping active_utils dependency to `~> 3.3.0`, to support changes implemented on https://github.com/Shopify/active_utils/pull/78 and https://github.com/Shopify/active_utils/pull/79.
Related PRs: https://github.com/Shopify/active_shipping/pull/490, https://github.com/Shopify/active_shipping/pull/492

Release version 1.12.0

---

lib/active_shipping/carriers/canada_post_pws.rb

Canada Post PWS is a non US carrier, add a default location similar to the other Canada Post carrier [here](https://github.com/Shopify/active_shipping/blob/84f971deff31dc13a44ed472a9b35c0e281eb452/lib/active_shipping/carriers/canada_post.rb#L97-L105)

add default location for CanadaPost PWS

---

lib/active_shipping/carriers/ups.rb
test/test_helper.rb
test/unit/carriers/ups_test.rb

Patch the `CountryCode` on a UPS XML request payload, changing the country code from `XK` to `KV` if necessary (Kosovo address).
In `ActiveUtils`, Kosovo's country code was recently updated from `KV` to `XK` (https://github.com/Shopify/active_utils/pull/79). UPS still uses Kosovo's old country code (`KV`), and will throw an invalid address if the new country code is used.

Patch UPS to use old Kosovo country code

---

lib/active_shipping/carriers/canada_post_pws.rb
test/unit/carriers/canada_post_pws_rating_test.rb

Sometimes tax is not desired in the rates lookup (eg, you are calculating your own tax)
Add an option to exclude tax from rate lookup. Also fixed the test fixture as the numbers were not lining up.

add option to not include tax in rates for CP PWS

---

lib/active_shipping/carriers/ups.rb
test/fixtures/xml/ups/location_node_kosovo_kv.xml
test/fixtures/xml/ups/location_node_kosovo_xk.xml
test/fixtures/xml/ups/location_node_zz.xml
test/unit/carriers/ups_test.rb

This PR fixes an issue where trying to parse tracking info for shipments that travel through (or end up in) Kosovo are raising `ActiveUtils::InvalidCountryCodeError: No country could be found for the country KV`
A little bit hacky, but fast.

fix up UPS tracker parsing for Kosovo (KV)

---

test/remote/usps_test.rb

Old tracking code expired so found a new one and updated test.

Fix failing remote USPS test

---

lib/active_shipping/carriers/canada_post_pws.rb
test/unit/carriers/canada_post_pws_test.rb

Canada Posts web service API is not every friendly with downcase'd postal codes. Therefore as part of removing whitespaces also `upcase`. Also add some tests around this behaviour.
Test failures are all remote UPS related seems like the API is having some issues
```
ActiveShipping::ResponseError: Failure: XML Rating and Service Selection Service Unavailable
```

Upcase postal code for CanadaPostPWS

---

lib/active_shipping/carriers/correios.rb
test/unit/carriers/correios_test.rb

Due to some API changes, the Correios' endpoint deprecated service codes 41106 and 40010, in favour of the new ones: '04510', and '04014'. This PR adds the new service codes and updates the list of default services.
- The new service codes must be used as is, with the leading zero. If used in the same format as the pre-existing ones, the request will fail.
- I did not update the existing services to strings to avoid having downstream problems. Maybe we can do that in the next major release.

Add new Correios service codes and update defaults

---

test/remote/ups_test.rb

Some of our remote UPS tests start failing on Thursday evening and keep failing throughout the remainder of the week because UPS considers Saturday as a business day.
Add Saturday as a business day for these tests.
cc @mdking

Make our remote UPS tests consider Saturday as a business day

---

lib/active_shipping/carriers/canada_post_pws.rb
test/fixtures/xml/canadapost_pws/merchant_details_response_no_contract_number.xml
test/unit/carriers/canada_post_pws_register_test.rb

According to the [docs](https://www.canadapost.ca/cpo/mc/business/productsservices/developers/services/ecomplatforms/registrationinfo.jsf)
> contract-number
> The contract number of the merchant if the merchant has a single contract. If the merchant does not have a contract, or has multiple contracts, no contract number will be returned.
Contract numbers are 10 digits. If the number provided is less than 10 digits, the system will add leading zeros.
Since this is an optional field in the response xml, this PR prevents raising an error when contract-number is missing.

Allow contract-number field in merchant response to be nil

---

lib/active_shipping/carriers/fedex.rb
test/fixtures/xml/fedex/ottawa_to_beverly_hills_no_saturday_rate_request.xml
test/unit/carriers/fedex_test.rb

There is no reason why we should be forcing possible saturday delivery rates when they are optional. Thus add a new option `saturday_delivery` for fedex that allows greater control over whether or not saturday delivery rates are displayed or not.

Make `SATURDAY_DELIVERY` and option for fedex

---

lib/active_shipping/location.rb
test/unit/location_test.rb

[Recent changes](https://github.com/Shopify/active_shipping/pull/446/files#diff-808f0e47ee0b93d89184bb01b6d1f652L67) to the code to read attributes for locations resulted in a very subtle change in behaviour for objects that have both hash access and methods that return values, such as ActiveRecord objects.
Example: An `Address` model with both `province` column and `province_code` method. We used to return "CA" but we now return "California", and we've always been missing a test around this behaviour.
The root cause of this is an interface that is exceptionally wide, and subsequent version of this library we will move to a more simple and explicit interface.

Adhere to property order if using objects with hash access.

---

lib/active_shipping/carriers/canada_post_pws.rb
test/unit/carriers/canada_post_pws_shipping_test.rb

Currently when we use `find_shipment_receipt` on Canada Post, in the case where the receipt is not found, `ssl_get` returns an `ActiveUtils::ResponseError`. This PR rescues that error and returns an `ActiveShipping::ResponseError` instead.
We should only be raising `ActiveShipping` errors in this gem.
With most carriers, we rescue bad API responses and build a corresponding variation of the `ActiveShipping::Response` object to return so that the method fails gracefully. 
The Canada Post receipt is tricky because when it's parsed, it doesn't return a `Response` object, rather it's just a hash. Rescuing and returning a `Response` object here doesn't make sense so I'm making sure it at least raises an `ActiveShipping` related error.
Closes …

Trap ActiveUtils::ResponseError and return ActiveShipping::ResponseError instead

---

CHANGELOG.md
lib/active_shipping/version.rb

Release version v2.0.1 with the changes implemented on https://github.com/Shopify/active_shipping/pull/524.

Bump to version 2.0.1
